import{a as d,i as l,S as u}from"./assets/vendor-0_SqCrma.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();const m="49366539-6fd412d088ca04dcc1c9b4bd7",f=e=>d.get("https://pixabay.com/api/",{params:{key:m,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0}}),p=()=>{const e=document.createElement("div");e.classList.add("loader"),document.body.appendChild(e)},c=()=>{const e=document.querySelector(".loader");e&&document.body.removeChild(e)},y=()=>{let e=document.querySelector(".gallery");e&&(e.innerHTML="")},h=()=>{let e=document.createElement("ul");return e.classList.add("gallery"),document.body.appendChild(e),e},g=(e,a)=>{e.forEach(r=>{const s=document.createElement("li");s.classList.add("gallery-item"),s.innerHTML=`
      <a href="${r.webformatURL}"><img src="${r.webformatURL}" alt="${r.tags}"></a>
      <div class="info">
        <p><b>Likes</b><br>${r.likes}</p>
        <p><b>Views</b><br>${r.views}</p>
        <p><b>Comments</b><br>${r.comments}</p>
        <p><b>Downloads</b><br>${r.downloads} </p>
      </div>
    `,a.appendChild(s)})},i=document.querySelector(".form");i.addEventListener("submit",function(e){e.preventDefault();const a=i.querySelector('input[name="search-text"]').value.trim();if(!a){l.error({title:"Error",message:"Please, enter the text for search!"});return}p();let r=document.querySelector(".gallery");r?y():r=h(),f(a).then(s=>{c();const t=s.data.hits;if(t.length===0){l.warning({title:"Caution",message:"Sorry, there are no images matching your search query. Please try again!"});return}g(t,r),new u(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}).catch(s=>{c(),l.error({title:"Error",message:"Illegal operation."}),console.error(s)})});
//# sourceMappingURL=index.js.map
