import{a as l,i as a}from"./assets/vendor-Dgf4FwRZ.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&i(o)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();l({method:"get",url:"https://jsonplaceholder.typicode.com/users"}).then(s=>console.log(s)).catch(s=>console.log(s));const c=document.querySelector(".form"),d="49366539-6fd412d088ca04dcc1c9b4bd7";c.addEventListener("submit",function(s){s.preventDefault();const n=c.querySelector('input[name="search-text"]').value.trim();if(!n){a.error({title:"Error",message:"Please, enter the text for search!"});return}let r=document.querySelector(".gallery");r?r.innerHTML="":(r=document.createElement("ul"),r.classList.add("gallery"),document.body.appendChild(r)),l.get("https://pixabay.com/api/",{params:{key:d,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(i=>{const e=i.data.hits;if(e.length===0){a.warning({title:"Caution",message:"Sorry, there are no images matching your search query. Please try again!"});return}e.forEach(t=>{const o=document.createElement("li");o.classList.add("gallery-item"),o.innerHTML=`
        <img src="${t.webformatURL}" alt="${t.tags}">
        <div class="info">
          <p><b>Likes</b><br>${t.likes}</p>
          <p><b>Views</b><br>${t.views}</p>
          <p><b>Comments</b><br>${t.comments}</p>
          <p><b>Downloads</b><br>${t.downloads} </p>
        </div>
      `,r.appendChild(o)})}).catch(i=>{a.error({title:"Error",message:"Illegal operation."}),console.error(i)})});
//# sourceMappingURL=index.js.map
