import{a as u,S as d,i as l}from"./assets/vendor-0_SqCrma.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&r(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const f="49366539-6fd412d088ca04dcc1c9b4bd7",m=t=>u.get("https://pixabay.com/api/",{params:{key:f,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0}});function p(){const t=document.querySelector(".loader");t&&(t.style.display="inline-block")}function i(){const t=document.querySelector(".loader");t&&(t.style.display="none")}const y=()=>{let t=document.querySelector(".gallery");t&&(t.innerHTML="")};function h(t){const a=document.querySelector(".gallery");t.forEach(r=>{const e=document.createElement("li");e.classList.add("gallery-item"),e.innerHTML=`
            <a href="${r.webformatURL}"><img src="${r.webformatURL}" alt="${r.tags}"></a>
            <div class="info">
                <p><b>Likes</b><br>${r.likes}</p>
                <p><b>Views</b><br>${r.views}</p>
                <p><b>Comments</b><br>${r.comments}</p>
                <p><b>Downloads</b><br>${r.downloads}</p>
            </div>
        `,a.appendChild(e)}),new d(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}const c=document.querySelector(".form");c.addEventListener("submit",function(t){t.preventDefault();const a=c.querySelector('input[name="search-text"]').value.trim();if(!a){l.error({title:"Error",message:"Please, enter the text for search!"});return}p();let n=document.querySelector(".gallery");n?y():n=createGallery(),m(a).then(r=>{i();const e=r.data.hits;if(e.length===0){l.warning({title:"Caution",message:"Sorry, there are no images matching your search query. Please try again!"});return}h(e),new d(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}).catch(r=>{i(),l.error({title:"Error",message:"Illegal operation."}),console.error(r)})});
//# sourceMappingURL=index.js.map
